// Package postgres provides the PostgreSQL dialect for the portable store in
// store/sql.
//
// Like the other dialect packages it imports no driver and opens no connections.
// Callers open their own *sql.DB with whichever driver they already depend on —
// pgx, lib/pq, anything implementing database/sql — and hand it to the store.
// The driver import stays in the caller's module, which is what keeps the
// library's dependency list empty.
//
// Typical wiring, where _ "github.com/jackc/pgx/v5/stdlib" is the caller's own
// import:
//
//	db, err := sql.Open("pgx", dsn)
//	if err != nil {
//		return err
//	}
//	store, err := sqlstore.Open(db, postgres.Dialect{})
package postgres

import (
	"database/sql"
	"fmt"
	"strconv"
	"strings"

	sqlstore "github.com/im10furry/distledger/store/sql"
)

// Dialect implements sqlstore.Dialect for PostgreSQL 12 and later.
type Dialect struct{}

var _ sqlstore.Dialect = Dialect{}

// Name implements sqlstore.Dialect.
func (Dialect) Name() string { return "postgres" }

// Placeholder implements sqlstore.Dialect. PostgreSQL numbers its parameters,
// so the position matters. That is the only reason the sqlstore argument builder
// tracks an index at all.
func (Dialect) Placeholder(n int) string { return "$" + strconv.Itoa(n) }

// Quote implements sqlstore.Dialect.
func (Dialect) Quote(name string) string { return `"` + strings.ReplaceAll(name, `"`, `""`) + `"` }

// TypeName implements sqlstore.Dialect.
func (Dialect) TypeName(kind sqlstore.ColumnKind, size int) string {
	switch kind {
	case sqlstore.KindInt64:
		return "BIGINT"
	case sqlstore.KindString:
		if size <= 0 {
			size = 255
		}
		return fmt.Sprintf("VARCHAR(%d)", size)
	case sqlstore.KindBytes:
		return "BYTEA"
	default:
		// Instants are Unix nanoseconds. BIGINT rather than TIMESTAMPTZ so that
		// every backend stores the same value for the same instant; a migration
		// between databases then cannot shift a settlement date.
		return "BIGINT"
	}
}

// TableSuffix implements sqlstore.Dialect. PostgreSQL needs no storage engine or
// charset suffix: both are database-level settings.
func (Dialect) TableSuffix() string { return "" }

// IndexDDL implements sqlstore.Dialect. PostgreSQL understands
// IF NOT EXISTS, so no error tolerance is needed for re-running migrations.
func (Dialect) IndexDDL(table, index string, cols []string, _ map[string]sqlstore.ColumnKind, unique bool) string {
	kind := "CREATE INDEX IF NOT EXISTS "
	if unique {
		kind = "CREATE UNIQUE INDEX IF NOT EXISTS "
	}
	quoted := make([]string, 0, len(cols))
	for _, c := range cols {
		quoted = append(quoted, (Dialect{}).Quote(c))
	}
	return fmt.Sprintf("%s%s ON %s (%s)",
		kind, (Dialect{}).Quote(index), (Dialect{}).Quote(table), strings.Join(quoted, ", "))
}

// AutoIDColumn implements sqlstore.Dialect.
//
// GENERATED BY DEFAULT AS IDENTITY is the SQL standard form and is preferred over
// the legacy SERIAL, which creates a sequence with surprising ownership rules.
// BY DEFAULT rather than ALWAYS so that a data migration may supply explicit ids.
func (Dialect) AutoIDColumn() string { return "BIGINT GENERATED BY DEFAULT AS IDENTITY" }

// AutoIDIsPrimary implements sqlstore.Dialect. PostgreSQL declares the key
// separately, as a table constraint.
func (Dialect) AutoIDIsPrimary() bool { return false }

// InsertID implements sqlstore.Dialect. PostgreSQL has no LastInsertId, so the
// store appends RETURNING.
func (Dialect) InsertID() sqlstore.InsertIDStrategy { return sqlstore.InsertIDReturning }

// InsertConflictClause implements sqlstore.Dialect.
//
// PostgreSQL needs it: a failed statement aborts the whole transaction, so a
// duplicate key cannot be caught and carried on from. ON CONFLICT DO NOTHING
// absorbs exactly the constraint collisions and lets every other error through.
func (Dialect) InsertConflictClause() string { return " ON CONFLICT DO NOTHING" }

// IsDuplicateKey implements sqlstore.Dialect.
func (Dialect) IsDuplicateKey(err error) bool { return sqlstore.Detect.IsDuplicateKey(err) }

// IsRetryable implements sqlstore.Dialect.
func (Dialect) IsRetryable(err error) bool { return sqlstore.Detect.IsRetryable(err) }

// IsAlreadyExists implements sqlstore.Dialect.
func (Dialect) IsAlreadyExists(err error) bool { return sqlstore.Detect.IsAlreadyExists(err) }

// Open wraps an already-open database handle with this dialect.
//
// It is a thin convenience over sqlstore.Open, and it exists so a caller does not
// have to name the dialect type explicitly. The handle is still the caller's: the
// library opens no connections and closes none.
func Open(db *sql.DB, opts ...sqlstore.Option) (*sqlstore.Store, error) {
	return sqlstore.Open(db, Dialect{}, opts...)
}
